---
  - name: Make ext4 filesystem on EBS volume
    command: mkfs -t ext4 /dev/xvdb

  - name: Create mount point
    file: path=/mnt state=directory
    ignore_errors: yes

  - name: Mount EBS volume at /mnt
    command: mount /dev/xvdb /mnt
