---
  - name: Creating data directory
    file: path=/mnt/data state=directory owner={{ kafka.user }} group={{ kafka.group }}


  - name: Updating kafka-serever-start - Java Heap Options
    template: src={{ item }} dest={{ common.soft_link_base_path }}/kafka/bin/{{ item }} owner={{ kafka.user }} group={{ kafka.group }}
    with_items:
      - kafka-server-start.sh
 
  - name: Updating Configuration File in kafka.
    template: src={{ item }} dest={{ common.soft_link_base_path }}/kafka/config/{{ item }} owner={{ kafka.user }} group={{ kafka.group }}
    with_items:
      - server.properties
      - log4j.properties
      - kafka_server_starter.sh

  - name: Creating a directory for kafka
    file: path={{ kafka.data_store }}/{{ broker_id }} owner={{ kafka.user }} group={{ kafka.group }} state=directory


  - name: Adding the path in the environment files
    lineinfile: dest=/home/kafkaadmin/.bashrc line='export PATH=$PATH:{{ common.soft_link_base_path }}/kafka/bin/' insertafter='EOF' regexp='export PATH=\$PATH:{{ common.soft_link_base_path }}/kafka/bin/' state=present

  - name: Source the enviroment file
    shell: source /home/kafkaadmin/.bashrc
