---

# Create user for `kafka`
- include_tasks: user.yml

# Install `kafka` - we are using tar.gz file to install `kafka`
- include_tasks: install.yml

# Configuration update server.properties, log4j, creating kafka starter script.
- include_tasks: configure.yml

# Starting Kafka server in port 9091
- include_tasks: start_server.yml

# Creating Topics for the first Time.
- include_tasks: create_topics.yml
